/*
NO2024051428132_深圳分行_零售断卡排查账户
因分行零售断卡排查账户管理类全量投诉数据归属及对数所需，现将总行客户之声系统（数仓底表：LV26_SPECIAL_RENOVATE）下载得到的投诉上传，
由于这些投诉无法匹配到具体深分客户（原因包含但不限于UID并非深分客户等），烦请总行协助基于提供的投诉单号从LV26_SPECIAL_RENOVATE表查得客户UID，根据UID匹配并返回如下字段
（1）客户UID
（2）客户UID归属分行 （3）客户号、户口序号、UID项下各卡号、各卡归属分行（如敏感也可只传客户号及户口序号） 
（3）在投诉日期当日及之前其名下各卡号在招行最近一笔管控记录，包括中止中非、资金留滞(冻结代码X19),及非柜面日限额调低记录等，包括管控日期、管控时间、管控子项、管控机构、管控备注、管控原因等
*/

DROP TABLE IF EXISTS ORDER_TMP; --103
CREATE TEMPORARY TABLE ORDER_TMP
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE) 
DISTRIBUTE  BY  HASH(WORK_ORDER_NUM)
AS
SELECT A.WORK_ORDER_NUM,B.CUSTOMERID,B.ACCOUNT_NUMBER,B.ID_NO,CAST(A.COMPLAINT_TIME AS DATE) AS COMPLAINT_TIME
FROM NDS_VHIS.NLV26_SPECIAL_RENOVATE A 
LEFT JOIN NDS_VHIS.NLV26_COMPLAINT_BASE B 
	ON A.WORK_ORDER_NUM = B.WORK_ORDER_NUM  -- 使用工单编号关联
WHERE UPPER(A.WORK_ORDER_NUM) IN ('20240506000010IM')
;

DROP TABLE IF EXISTS UID_TMP; --103
CREATE TEMPORARY TABLE UID_TMP
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE) 
DISTRIBUTE  BY  HASH(WORK_ORDER_NUM)
AS
SELECT A.WORK_ORDER_NUM,C.CUST_UID,COMPLAINT_TIME
FROM ORDER_TMP A
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.EAC_ID = A.ACCOUNT_NUMBER
	AND C.DW_SNSH_DT= CURRENT_DATE -1
UNION 
SELECT A.WORK_ORDER_NUM,C.CUST_UID,COMPLAINT_TIME
FROM ORDER_TMP A
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_ID = A.CUSTOMERID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
WHERE A.CUSTOMERID <>''
UNION 
SELECT A.WORK_ORDER_NUM,C.CUST_UID,COMPLAINT_TIME
FROM ORDER_TMP A
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_UID = A.CUSTOMERID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
WHERE A.CUSTOMERID <>''
UNION 
SELECT A.WORK_ORDER_NUM,C.CUST_UID,COMPLAINT_TIME
FROM ORDER_TMP A
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.OPN_DOC_NBR = A.ID_NO
	AND C.DW_SNSH_DT= CURRENT_DATE -1
WHERE A.ID_NO <>''
;

--匹配管控记录
DROP TABLE IF EXISTS SSP_TMP; --155
CREATE TEMPORARY TABLE SSP_TMP
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE) 
DISTRIBUTE  BY  HASH(EAC_ID)
AS
SELECT 
C.EAC_ID
,COALESCE(CAST(REPLACE(B.REG_DT,'-','') AS VARCHAR),'00010101') 管控日期
,COALESCE(CAST(REPLACE(B.REG_TM,':','') AS VARCHAR),'010101') 管控时间
,CASE B.SSP_TYP_CD WHEN  'A' THEN  '中止所有业务'
	WHEN  'B' THEN  '中止非柜面业务'
	WHEN  'C' THEN  '中止快捷支付业务'
	WHEN  'D' THEN  '停止支付业务' 
	ELSE '未匹配到中止数据' END AS "管控类型"
,COALESCE(SSP_SUB_ITM,'') 管控子项
,COALESCE(D.ORG_NM,'') 管控机构
,COALESCE(CMT,'') 管控备注
,''  管控原因
--,ROW_NUMBER() OVER(PARTITION BY C.EAC_ID ORDER BY REG_DT DESC)AS RANK1
FROM UID_TMP S
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_UID = S.CUST_UID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
INNER JOIN PDM_VHIS.T01_TLCM_FRD_SSP_BUS_INF_FILE B
	ON B.EAC_ID = C.EAC_ID 
	AND B.REG_DT < S.COMPLAINT_TIME
LEFT JOIN AMIP_VHIS.AMIP_D_ORG_VAL D
	ON D.ORG_ID = B.REG_ORG_ID
	AND D.ORG_ID <> ''
GROUP BY 1,2,3,4,5,6,7,8
;


--资金留滞(冻结代码X19)
INSERT INTO SSP_TMP
SELECT DISTINCT
C.EAC_ID
,COALESCE(CAST(REPLACE(B.FRZ_REG_DT,'-','') AS VARCHAR),'00010101') 管控日期
,COALESCE(CAST(REPLACE(B.FRZ_REG_TM,':','') AS VARCHAR),'010101') 管控时间
,COALESCE(B.FRZ_CD,'') "管控类型"
,'' 管控子项
,COALESCE(D.ORG_NM,'') 管控机构
,'' 管控备注
,'' 管控原因
FROM UID_TMP S
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_UID = S.CUST_UID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
LEFT JOIN PDM_VHIS.T03_CORE_ACT_AGR_FRZ_INF_S B--核心账户协议冻结信息快照
	ON C.EAC_ID = B.EAC_ID
	AND B.FRZ_CD = 'X19'
	AND B.FRZ_REG_DT <= S.COMPLAINT_TIME
LEFT JOIN AMIP_VHIS.AMIP_D_ORG_VAL D
	ON D.ORG_ID = B.FRZ_REG_ORG_ID
	AND D.ORG_ID <> ''
;

--限额管控 
INSERT INTO SSP_TMP
SELECT DISTINCT
C.EAC_ID
,COALESCE(CAST(REPLACE(B.DW_DAT_DT,'-','') AS VARCHAR),'00010101') 管控日期
,'010101' 管控时间
,'限额管控'AS "管控类型"
,'' 管控子项
,COALESCE(D.ORG_NM,'') 管控机构
,'' 管控备注
,COALESCE(TRX_LMT_RSN,'') 管控原因
FROM UID_TMP S
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_UID = S.CUST_UID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
LEFT JOIN NDS_VHIS.NLW66_DEC_LMT_TRX_T B	--非柜面支出限额交易表
	ON C.EAC_ID = B.TRX_EAC_NBR
	AND B.TRX_LMD_FLG = 'Y'
	AND B.TRX_REA_LMD < B.TRX_OLD_LMD
	AND B.DW_DAT_DT <= S.COMPLAINT_TIME
LEFT JOIN AMIP_VHIS.AMIP_D_ORG_VAL D
	ON D.ORG_ID = B.TRX_TRX_BRN
	AND D.ORG_ID <> ''
;

DROP TABLE IF EXISTS RES_TMP1;
CREATE TEMPORARY TABLE RES_TMP1
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE) 
AS
SELECT 
EAC_ID
,管控日期
,管控时间
,管控类型
,管控子项
,管控机构
,管控备注
,管控原因
,ROW_NUMBER() OVER(PARTITION BY EAC_ID ORDER BY 管控日期 DESC)AS RANK1
FROM SSP_TMP
;

SELECT DISTINCT 
S.WORK_ORDER_NUM 工单
,S.CUST_UID AS "客户UID"
,S6.BLG_FRS_BBK_ORG_ID "UID归属分行"
,C.EAC_ID 
,C.CUST_ID
,C.EAC_SEQ_NBR 户口序号
,D.ORG_NM 开户机构  
,B.管控日期
,B.管控时间
,B.管控类型
,B.管控子项
,B.管控机构
,B.管控备注
,B.管控原因
FROM UID_TMP S
INNER JOIN SUM_VHIS.T83_EAC_INF_S C
	ON C.CUST_UID = S.CUST_UID
	AND C.DW_SNSH_DT= CURRENT_DATE -1
LEFT JOIN BRTL_VIEW.BRTL_SR_RTL_BBK_CUST_S AS S6          /* SR_零售分行客户快照 */     
	ON S.CUST_UID = S6.CUST_UID
	AND S6.DW_SNSH_DT = CURRENT_DATE -1  
LEFT JOIN RES_TMP1 B
	ON B.EAC_ID = C.EAC_ID 
	AND RANK1 = 1
LEFT JOIN AMIP_VHIS.AMIP_D_ORG_VAL D
	ON D.ORG_ID = C.OPN_ORG_ID
	AND D.ORG_ID <> ''
;

/*
NO***********_重庆分行_信用卡指标数据
1、全重庆地区的24年1-6月交易量和交易金额，以及同比去年的值
2、全重庆地区的裸信用卡客户量（仅持有信用卡，未持有储蓄卡）
3、全重庆地区的裸信用卡客户中，仅通过柜面、ATM机还款等传统渠道还款的客户数

BCRD_VHIS.BCRD_S_CARD		--S层卡片档
BCRD_VHIS.BCRD_B_IDV_APL		--个人申请书表
ARTS_VHIS.ARTS_A_RTL_CUST_BAS_INF_S	--零售客户基本信息快照
BRTL_VCOH.BRTL_PH_EAC_INF_S	--PH_外部户口信息快照
*/

--2、全重庆地区的裸信用卡客户量（仅持有信用卡，未持有储蓄卡） 536031
SELECT COUNT(DISTINCT INF.CUST_UID) 全量信用卡客户数,COUNT(DISTINCT CASE WHEN EAC.OPN_DT IS NULL THEN INF.CUST_UID ELSE NULL END) AS 裸信用卡客户量
FROM BCRD_VHIS.BCRD_S_CARD BASE --S层卡片档
INNER JOIN BCRD_VHIS.BCRD_B_IDV_APL APL 
	ON APL.APL_NBR = BASE.APL_NBR
INNER JOIN ARTS_VHIS.ARTS_A_RTL_CUST_BAS_INF_S INF 
	ON REPLACE(APL.CTF_NBR,'P01','') = INF.DOC_NBR
	AND INF.DW_SNSH_DT = '2024-07-20'
LEFT JOIN BRTL_VCOH.BRTL_PH_EAC_INF_S EAC
	ON INF.CUST_UID = EAC.CUST_UID
	AND EAC.DW_SNSH_DT = '2024-06-30'
	AND EAC.RTL_EAC_STS_CD  = '3003' --限制非注销客户
	AND EAC.EAC_CD IN ('301','302','386') --限制一类户和面核二类户
	AND EAC.RTL_EAC_TYP_CD = 'COR' --限制借记卡账户
WHERE BASE.SAL_CD IN (SELECT PRMT_CD FROM BCRD_VHIS.BCRD_B_PRMT_PARM WHERE  PRMT_SUP_ORG_NM LIKE '%重庆%')
;

--3、全重庆地区的裸信用卡客户中，仅通过柜面、ATM机还款等传统渠道还款的客户数  57157

--取信用卡裸卡客户 --2180162
DROP TABLE IF EXISTS RES_TMP;
CREATE TEMPORARY TABLE RES_TMP
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE)
DISTRIBUTE  BY  HASH(PRM_CUST_ID)
AS
SELECT BASE.PRM_CUST_ID,INF.DOC_NBR,CASE WHEN EAC.OPN_DT IS NULL THEN 'Y' ELSE 'N' END AS "是否裸信用卡客户"
FROM BCRD_VHIS.BCRD_S_CARD BASE --S层卡片档
INNER JOIN BCRD_VHIS.BCRD_B_IDV_APL APL 
	ON APL.APL_NBR = BASE.APL_NBR
INNER JOIN ARTS_VHIS.ARTS_A_RTL_CUST_BAS_INF_S INF 
	ON REPLACE(APL.CTF_NBR,'P01','') = INF.DOC_NBR
	AND INF.DW_SNSH_DT = '2024-07-20'
LEFT JOIN BRTL_VCOH.BRTL_PH_EAC_INF_S EAC
	ON INF.CUST_UID = EAC.CUST_UID
	AND EAC.DW_SNSH_DT = '2024-06-30'
	AND EAC.RTL_EAC_STS_CD  = '3003' --限制非注销客户
	AND EAC.EAC_CD IN ('301','302','386') --限制一类户和面核二类户
	AND EAC.RTL_EAC_TYP_CD = 'COR' --限制借记卡账户
WHERE BASE.SAL_CD IN (SELECT PRMT_CD FROM BCRD_VHIS.BCRD_B_PRMT_PARM WHERE  PRMT_SUP_ORG_NM LIKE '%重庆%')
GROUP BY 1,2,3
;

SELECT COUNT(DISTINCT RES.DOC_NBR)
FROM RES_TMP RES
INNER JOIN PDM_VHIS.T05_AS400_CRD_CARD_IDV_PAY_EVT AS400 
	ON AS400.CUST_ID = RES.PRM_CUST_ID
	AND AS400.PAY_CHNL_TYP_CD IN ('T00','T01','T03','T32','T55','T08','T09')
WHERE "是否裸信用卡客户" = 'Y'


/*
NO***********_沈阳分行_基金购买及风评
申请提取客户李海英，客户号***********，2021年11月29日投资兴全汇虹基金产品，
产品代码010981；2022年4月7日投资广发养老FOF,投资日期2024年4月7日，包含产品购买前客户经理的W+接触记录，产品购买渠道，客户风评渠道等信息。
*/

DROP TABLE IF EXISTS LC_TMP;
CREATE TEMPORARY TABLE LC_TMP         
WITH (ORIENTATION = COLUMN, COLVERSION = 2.0, COMPRESSION = MIDDLE)
DISTRIBUTE BY HASH (EAC_ID)
AS (
	SELECT EAC_ID,IAC_ID, CUST_NM,CUST_ID
	FROM SUM_VHIS.T83_EAC_INF_S 
	WHERE DW_SNSH_DT = CURRENT_DATE-1
	AND CUST_ID = '***********'
)
WITH DATA;



SELECT 
	H.CUST_NM 				AS 账户名
	,B.EAC_ID  				AS 账户编号
	,B.TRX_OBJ_ID 		AS 交易标的编号
	,B.DT	申请日期
	,B.TM	申请时间
	,C.FND_FND_INN				AS 基金代码
	,C.FND_FUL_NAM    		AS 产品中文名称
	--,C.FND_PROD_TYP_NM 		AS 基金产品类型名称
	,C.FND_CRP_MID		AS 基金管理公司名称
	,C.FND_CRP_COD		AS 基金管理公司代码
	,B.ENTR_AMT				AS 委托金额
	,B.FND_TRX_AMT 			AS 资金交易金额
	,B.FEE_AMT				AS 费用金额
	,CASE TRX_CD 
		WHEN 'FDE1'	THEN '签署约定书' WHEN 'FDE2'	THEN '撤销约定书' WHEN 'FDE3'	THEN '签电子合同' WHEN 'FDE4'	THEN '签纸质合同' WHEN 'FD01'	THEN '开户' WHEN 'FD02'	THEN '关户' WHEN 'FD03'	THEN '修改资料' WHEN 'FD04'	THEN '账户冻结' WHEN 'FD05'	THEN '账户解冻' WHEN 'FD06'	THEN '挂失' WHEN 'FD07'	THEN '解挂' WHEN 'FD08'	THEN '增加交易账号' WHEN 'FD09'	THEN '撤销交易账号' WHEN 'FD2D'	THEN '认购利息' WHEN 'FD2F'	THEN '预约购买' WHEN 'FD20'	THEN '认购' WHEN 'FD22'	THEN '申购' WHEN 'FD24'	THEN '赎回' WHEN 'FD26'	THEN '转托管' WHEN 'FD27'	THEN '持仓转入' WHEN 'FD28'	THEN '持仓转出' WHEN 'FD29'	THEN '修改分红方式' WHEN 'FD30'	THEN '认购结果' WHEN 'FD31'	THEN '基金份额冻结' WHEN 'FD32'	THEN '基金份额解冻' WHEN 'FD34'	THEN '非交易过户转入' WHEN 'FD35'	THEN '非交易过户转出' WHEN 'FD36'	THEN '基金转换' WHEN 'FD37'	THEN '基金转换转入' WHEN 'FD38'	THEN '基金转换转出' WHEN 'FD39'	THEN '定时定额投资' WHEN 'FD42'	THEN '强行赎回' WHEN 'FD43'	THEN '红利' WHEN 'FD44'	THEN '强行调增' WHEN 'FD45'	THEN '强行调减' WHEN 'FD49'	THEN '募集失败' WHEN 'FD5A'	THEN '定期赎回申请' WHEN 'FD5B'	THEN '条件申购申请' WHEN 'FD5C'	THEN '条件赎回申请' WHEN 'FD5D'	THEN '条件计划撤回' WHEN 'FD50'	THEN '基金清盘' WHEN 'FD52'	THEN '撤单' WHEN 'FD59'	THEN '定期定额申请' WHEN 'FD60'	THEN '定期定额撤销' WHEN 'FD61'	THEN '定期定额修改' WHEN 'FD98'	THEN '快速赎回' WHEN 'FDLB'	THEN '受益权受让' WHEN 'FDLS'	THEN '受益权出让'
		ELSE TRX_CD
		END 				AS 投资理财交易代码
	,CASE B.TRX_CHNL_TYP_CD
		WHEN 'TEL' THEN '电话语音'
		WHEN 'TGS' THEN '托管银行清算系统'
		WHEN 'BCK' THEN '后台'
		WHEN 'CAL' THEN '电话人工'
		WHEN 'DSK' THEN '柜台'
		WHEN 'FSY' THEN '金融平台'
		WHEN 'ICO' THEN '企业银行'
		WHEN 'IEX' THEN '个人银行专业版'
		WHEN 'INT' THEN '个人银行大众版'
		WHEN 'MPH' THEN '手机银行'
		ELSE B.TRX_CHNL_TYP_CD 
		END AS 交易渠道
		,TRX_BBK_ORG_ID 交易分行机构编号
	,TRX_ORG_ID 交易机构编号
	--,B.RCM_PSN_ID			AS 推荐人编号1  --这个字段和推荐人无关，段祥越
	,COALESCE(
		IF(D.INT_RCM_PSN_1_NBR = '',NULL,D.INT_RCM_PSN_1_NBR),
		IF(D.INT_RCM_PSN_2_NBR = '',NULL,D.INT_RCM_PSN_2_NBR),
		IF(D.INT_RCM_PSN_3_NBR = '',NULL,D.INT_RCM_PSN_3_NBR),
		IF(D.EXT_RCM_PSN_NBR = '',NULL,D.EXT_RCM_PSN_NBR),
		IF(D.SLF_RCM_PSN_NBR = '',NULL,D.SLF_RCM_PSN_NBR),
		''
		)AS 推荐人编号
	,SUBSTRING(C.FND_FND_TYP, 5,1)  			AS 风险等级
	, ANA_NO 分析码


	/*
NO2024052115936_上海分行_ATM小额取现
申请提取2024.03.01-03.31及2024.04.01-04.30两月份的ATM小额取现数据
*/


--不限制境内外  
CREATE TEMPORARY TABLE RHQX_TMP
AS(
SELECT DISTINCT
TRS_TRS_DAT --取现日期
,TRS_TRS_PAN --账号
,TRS_ATM_SEQ --流水号
,TRS_BNK_INFO --渠道标识
,TRS_TRS_CUR --取现币种
,TRS_TRS_AMT --取现金额
,A.TRS_TRM_NBR --受卡方渠道编号
FROM NDS_VHIS.NLW12_PTA_FINANCIAL_TRADE_T A
WHERE TRS_TRS_TYP='CWD'
AND TRS_TRS_AMT <> 0
AND TRS_TRS_AMT%100 <>0
AND TRS_TRS_DAT	BETWEEN '2024-04-01' AND  '2024-04-30'
AND TRS_TRS_STS	='S'
)WITH DATA;

SELECT 
A.TRS_TRM_NBR
,COUNT(TRS_ATM_SEQ) 笔数
,SUM(TRS_TRS_AMT )取现金额
FROM RHQX_TMP A
WHERE  A.TRS_TRM_NBR IN ('002191W7','002191W8','002191M8','002191E2','0021919Y','0021919D','002191T4','002191R1','0021916K','0021914K','0021914N','002191N6','0021916T','0021918P','002191M4','0021919H','002191L1','002191K2','002191F9','002191I4','0021917H','0021917F','0021918Z','0021918V','002191S8','0021915H','0021916P','0021919R','0021916Z','002191V6','002191G4','002191X7','002191R5','002191Q3','0021915Q','002191K5','002191R7','0021918A','0021916D','0021919Q','002191P9','0021893Q','002191M7','002191T2','00213161','00217464','00210761','00210861','00210501','00218928','0021891T','00219148','00218970')
GROUP BY 1

FROM PDM_VHIS.T05_FND_TRX_APL_EVT B
INNER JOIN LC_TMP  H
	ON B.EAC_ID = H.EAC_ID
LEFT JOIN NDS_VHIS.NLK02_TFE_FND_DEF_T C --补充到原始口径，没有关联条件，需要再问问看
	ON B.TRX_OBJ_ID= 'LK02'||C.FND_FND_INN||C.FND_SAA_COD
	--AND SUBSTRING(C.FND_FND_TYP, 2,1) IN ('A','B')  公募或私募由业务自行判断，类型可以看 孙晓梦的聊天记录
LEFT JOIN PDM_VHIS.T03_FND_RCM_INF D
	ON B.MSG_APL_ID = D.RCM_SRL
	;

--客户投资风险承受能力评估信息
SELECT DISTINCT
SYS_CD 系统代码,CUST_ID 客户编号,TOT_ASES_TMS 总评估次数,ASES_START_DT 评估开始日期,ASES_ORIG_TM 评估开始时间,ASES_MTU_DT 评估到期日期,CARD_NBR 银行卡号,CUST_BTH_DT 客户出生日期,CUST_CTC_TEL 客户联系电话,ASES_IND 已评估标志,ASES_BBK_ORG_ID 评估分行机构编号,ASES_ORG_ID 评估机构编号,AFL_BBK_ORG_ID 所属分行机构编号,AFL_ORG_ID 所属机构编号,CUST_NO_INV_EXP_IND 客户无投资经验标志,QST_CD 问卷代码,QST_NO 题目码,ASES_ANS 评估答案,ASES_SCO 评估得分,RSK_ENDU_CD 风险承受代码,
case CHNL_TYP_CD when 'DSK' then '柜面'	when 'IEX' then '网银'	else CHNL_TYP_CD end as 渠道类型代码,
HDL_USR_ID 经办用户编号,HDL_DT 经办日期,OPR_TM 经办时间,CHK_USR_ID 复核用户编号,CHK_DT 复核日期,ESP_NO_20 "特殊码20",CNT_ASES_DONE 柜面做过评估,MRG_IND_CD 合并标志代码
FROM PDM_VHIS.T01_CUST_IRT_ASES_INF
WHERE CUST_ID = '***********'
ORDER BY ASES_START_DT;


--问卷及答案
SELECT distinct QST_CD 问卷代码,PROB_CD 问题代码,SYS_CD 系统代码,PROB_DSCR 问题描述
--QST_START_DT 问卷开始日期,QST_MTU_DT 问卷到期日期,DW_START_DT 开始日期,DW_END_DT 结束日期
FROM PDM_VHIS.T00_CUST_IRT_ASES_QST_PARM --客户投资风险承受能力评估问卷参数表
WHERE SYS_CD = 'FI' and QST_CD IN( '003','004')
ORDER BY 3,1,2;

SELECT ANS_CD 答案代码,PROB_CD 问题代码,SYS_CD 系统代码,QST_CD 问卷代码,ANS_DSCR 答案描述,ANS_BRF 答案简述,ANS_VAL 答案分值,REF_PROD_LVL_CD 参考产品级别代码,REF_RSK_ENDU_CD 参考风险承受代码
--,QST_START_DT 问卷开始日期,QST_MTU_DT 问卷到期日期,DW_START_DT 开始日期,DW_END_DT 结束日期
FROM PDM_VHIS.T00_CUST_IRT_ASES_ANS_PARM --客户投资风险承受能力评估问卷答案参数表
WHERE SYS_CD = 'FI' and QST_CD IN( '003','004')
AND QST_MTU_DT = '9999-12-31'
ORDER BY 3,4,2,1,5
;

